app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  clients:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com/2.3
  bot-api: ${SCRAPPER_BASE_URL:http://localhost:8080}

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
